name: budget_fusion_app
description: "Budget Book mobile app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  keep_screen_on: ^3.0.0
  double_back_to_close_app: ^2.1.0
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  settings_ui: ^2.0.2
  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  logger: ^2.4.0
  form_validator: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  provider: ^6.1.2
  math_expressions: ^2.6.0
  community_material_icon: ^5.9.55
  collection: ^1.18.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  flutter_typeahead: ^5.2.0
  flutter_shake_animated: ^0.0.5
  package_info_plus: ^8.1.0
  easy_localization: ^3.0.7
  app_links: ^6.3.2
  google_sign_in: ^6.2.1
  get_it: ^8.0.1
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  decimal: ^3.0.2
  synchronized: ^3.3.0+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  uuid: ^4.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  rxdart: ^0.28.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

# For information on the generic Dart part of this file, see the
# following drawer: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/splash.png
    - assets/logo.png
    - assets/translations/
    - assets/categories.json
    - assets/category_icons.json
    - assets/migrations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # budget_fusion:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# run 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/logo-background.png"
  adaptive_icon_foreground: "assets/logo.png"

#run 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  color: "#303030"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleToFill
