name: budget_fusion_app
description: "Budget Book mobile app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  keep_screen_on: ^4.0.0
  double_back_to_close_app: ^2.1.0
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^6.0.0
  settings_ui: ^2.0.2
  intl: '>=0.19.0 <0.21.0'
  connectivity_plus: ^6.1.4
  logger: ^2.5.0
  form_validator: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.10
  provider: ^6.1.5
  math_expressions: ^3.1.0
  community_material_icon: ^5.9.55
  collection: ^1.18.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_typeahead: ^5.2.0
  flutter_shake_animated: ^0.0.5
  package_info_plus: ^8.3.0
  easy_localization: ^3.0.7+1
  app_links: ^6.4.0
  google_sign_in: ^7.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  decimal: ^3.0.2
  synchronized: ^3.3.1
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.0
  sqflite: ^2.4.2
  path: ^1.9.0
  rxdart: ^0.28.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  haptic_feedback: ^0.5.1+1
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4

dependency_overrides:
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:

  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/splash.png
    - assets/logo.png
    - assets/logo-full.png
    - assets/translations/
    - assets/category_icons.json
    - assets/migrations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # budget_fusion:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

#run 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  color: "#303030"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleToFill
