name: Flutter CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Flutter test
        run: flutter test
